In [1]:
# read CSV using a relative path
import pandas as pd
import requests
URL='http://api_mysql.tv4e.pt/api/recommendations/users'
data= requests.get(URL)
df=pd.DataFrame(data.json())

In [2]:
df.head()

,city_id,user_age,user_coordinates,user_gender,user_id,user_name
0,3,74,"40.6311386,-8.6574267",M,1,Dev
1,3,85,XXX,M,2,XXX
2,5,80,"40.4796835,-8.4561561",M,3,David Campelo
3,5,65,"40.629803,-8.608807",M,4,Francisco Silva
4,5,58,"40.6023542,-8.5682549",M,6,Sir Ian

In [3]:
df.city_id.unique()

array([ 3,  5, 12,  2])

In [5]:
# read CSV using a relative path
import pandas as pd
import requests
URL='http://api_mysql.tv4e.pt/api/recommendations/ratings'
data= requests.get(URL)
df=pd.DataFrame(data.json())

In [6]:
df

,rating_date_creation,rating_value,user_id,video_id,video_watch_time,video_watched_type
0,2018-01-14 11:02:42,NaN,1,5225,4,injected
1,2017-12-07 02:30:00,1.0,3,4448,87,notified
2,2017-12-06 22:00:01,-1.0,3,4576,100,notified
3,2017-12-07 02:00:00,1.0,3,4617,23,notified
4,2017-12-06 23:00:04,NaN,3,4674,100,notified
5,2017-12-06 23:30:01,-1.0,3,4699,100,notified
6,2017-12-05 11:00:00,0.0,3,4700,8,notified
7,2017-12-06 22:30:01,NaN,3,4706,55,notified
8,2017-12-02 05:00:00,NaN,3,4720,40,notified
9,2017-12-02 03:30:00,NaN,3,4724,100,notified
10,2017-12-01 23:00:00,1.0,3,4726,100,notified
11,2017-12-01 23:30:00,NaN,3,4728,100,notified
12,2017-12-05 14:30:01,1.0,3,4746,100,notified
13,2017-12-05 14:00:00,1.0,3,4747,90,notified
14,2017-12-05 12:00:00,NaN,3,4749,9,notified
15,2017-12-07 05:00:00,NaN,3,4763,33,notified
16,2017-12-07 04:00:00,0.0,3,4765,5,notified
17,2017-12-07 03:00:00,-1.0,3,4767,6,notified
18,2017-12-22 16:13:12,0.0,4,4775,100,forced
19,2017-12-22 16:12:07,1.0,4,4779,100,forced
20,2017-12-22 16:09:20,1.0,4,4851,7,forced
21,2017-12-22 16:08:02,NaN,4,4889,4,forced
22,2017-12-22 16:05:37,0.0,4,4905,100,forced
23,2017-12-22 16:03:26,0.0,4,4931,100,forced
24,2017-12-22 15:52:11,0.0,4,4943,100,forced
25,2017-12-22 15:42:44,0.0,4,4957,3,forced
26,2017-12-22 16:30:00,0.0,4,4962,100,injected
27,2017-12-22 15:44:36,1.0,4,4963,5,forced
28,2017-12-22 15:48:21,0.0,4,4976,14,forced
29,2018-01-11 15:51:50,1.0,4,5035,2,forced
...,...,...,...,...,...,...
461,2017-12-12 09:00:01,0.0,23,4811,90,notified
462,2017-12-14 16:00:01,0.0,23,4880,100,notified
463,2017-12-13 19:30:00,0.0,24,4861,100,injected
464,2017-12-16 10:30:00,NaN,24,4891,100,injected
465,2017-12-18 21:30:01,NaN,24,4907,100,injected
466,2017-12-18 18:22:16,0.0,24,4908,100,forced
467,2017-12-18 21:00:01,0.0,24,4909,100,injected
468,2017-12-18 20:00:01,0.0,24,4910,100,injected
469,2017-12-18 19:30:01,NaN,24,4911,100,injected
470,2017-12-18 19:00:01,NaN,24,4912,100,injected
471,2017-12-18 18:30:01,NaN,24,4913,100,injected
472,2017-12-18 20:30:01,0.0,24,4914,100,injected
473,2017-12-19 05:30:00,NaN,24,4916,100,injected
474,2017-12-19 22:00:01,NaN,24,4922,100,injected
475,2017-12-20 18:33:11,NaN,24,4939,93,forced
476,2017-12-20 18:40:40,0.0,24,4943,100,forced
477,2017-12-21 16:30:00,NaN,24,4956,1,notified
478,2017-12-10 15:30:00,NaN,25,4710,1,notified
479,2017-12-10 15:00:00,1.0,25,4712,100,notified
480,2017-12-06 08:30:00,0.0,25,4747,100,notified
481,2017-12-05 10:00:00,0.0,25,4751,100,notified
482,2017-12-05 09:30:00,NaN,25,4752,15,notified
483,2017-12-12 17:00:00,NaN,25,4825,100,notified
484,2017-12-12 07:00:00,1.0,25,4827,84,notified
485,2017-12-12 17:30:00,NaN,25,4831,2,notified
486,2017-12-17 14:00:00,0.0,25,4893,100,injected
487,2017-12-17 15:00:00,0.0,25,4905,1,injected
488,2017-12-17 14:30:01,NaN,25,4906,100,injected
489,2017-12-18 17:30:00,NaN,25,4910,100,injected
490,2017-12-18 17:00:00,0.0,25,4911,100,injected

In [11]:
# read CSV using a relative path
import pandas as pd
import requests
URL='http://api_mysql.tv4e.pt/api/recommendations/ratings'
data= requests.get(URL)
df=pd.DataFrame(data.json())

df = df[df.video_watched_type != 'forced']

# XXX use a function to calculate implicit rating considering the video lead time
df['rating_implicit'] = (df['video_watch_time']/100) * 0.3
df['rating_explicit'] = (df['rating_value'])         * 0.7
# If the explicit rating was negative, the implicit will be negative
df['rating_implicit'][df.rating_explicit < 0] = df['rating_implicit'] * -1
# create a new column to put implicit or explicit rating rating_value
df['overall_rating_value'] = df['rating_implicit'] + df['rating_explicit']

# implicit rating is the watched time / explicit rating is the like-0-dislike
df['rating_implicit'] = df['video_watch_time']/100
df['rating_explicit'] = df['rating_value']

df.loc[pd.isnull(df['rating_value']) & (df['video_watch_time'] >= 10),'overall_rating_value'] = (df['video_watch_time']/100) * 0.5

df.loc[(df['video_watch_time'] < 10),'overall_rating_value'] = 0
df['overall_rating_value']=df['overall_rating_value'].fillna(0)

import datetime
NOW = datetime.datetime.now()
df['rating_date_diff'] = NOW - pd.to_datetime(df['rating_date_creation'])
df = df[(df.rating_date_diff.dt.days < 14)]

# df = df[df.video_watch_time < 10]
df

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,rating_date_creation,rating_value,user_id,video_id,video_watch_time,video_watched_type,rating_implicit,rating_explicit,overall_rating_value,rating_date_diff
28,2018-02-15 15:42:05,NaN,1,5657,100,injected,1.00,NaN,0.5,1 days 01:03:13.856523
123,2018-02-15 20:59:42,NaN,9,5731,6,notified,0.06,NaN,0.0,0 days 19:45:36.856523
204,2018-02-16 16:14:48,NaN,30,5747,100,injected,1.00,NaN,0.5,0 days 00:30:30.856523

In [49]:
import numpy as np
for index, row in df.iterrows():
    print("explicit = {}".format(row.rating_explicit))
    if row.rating_explicit:
        print("index = {} row = {}".format(index,row))

explicit = nan
index = 1 row = rating_date_creation    2018-01-14 21:04:22
rating_value                            NaN
user_id                                   1
video_id                               5227
video_watch_time                         67
video_watched_type                 injected
rating_implicit                        0.67
rating_explicit                         NaN
overall_rating_value                  0.335
Name: 1, dtype: object
explicit = 1.0
index = 2 row = rating_date_creation    2017-12-07 02:30:00
rating_value                              1
user_id                                   3
video_id                               4448
video_watch_time                         87
video_watched_type                 notified
rating_implicit                        0.87
rating_explicit                           1
overall_rating_value                  0.961
Name: 2, dtype: object
explicit = -1.0
index = 3 row = rating_date_creation    2017-12-06 22:00:01
rating_value                             -1
user_id                                   3
video_id                               4576
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                          -1
overall_rating_value                     -1
Name: 3, dtype: object
explicit = 1.0
index = 4 row = rating_date_creation    2017-12-07 02:00:00
rating_value                              1
user_id                                   3
video_id                               4617
video_watch_time                         23
video_watched_type                 notified
rating_implicit                        0.23
rating_explicit                           1
overall_rating_value                  0.769
Name: 4, dtype: object
explicit = nan
index = 5 row = rating_date_creation    2017-12-06 23:00:04
rating_value                            NaN
user_id                                   3
video_id                               4674
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 5, dtype: object
explicit = -1.0
index = 6 row = rating_date_creation    2017-12-06 23:30:01
rating_value                             -1
user_id                                   3
video_id                               4699
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                          -1
overall_rating_value                     -1
Name: 6, dtype: object
explicit = nan
index = 8 row = rating_date_creation    2017-12-06 22:30:01
rating_value                            NaN
user_id                                   3
video_id                               4706
video_watch_time                         55
video_watched_type                 notified
rating_implicit                        0.55
rating_explicit                         NaN
overall_rating_value                  0.275
Name: 8, dtype: object
explicit = nan
index = 9 row = rating_date_creation    2017-12-02 05:00:00
rating_value                            NaN
user_id                                   3
video_id                               4720
video_watch_time                         40
video_watched_type                 notified
rating_implicit                         0.4
rating_explicit                         NaN
overall_rating_value                    0.2
Name: 9, dtype: object
explicit = nan
index = 10 row = rating_date_creation    2017-12-02 03:30:00
rating_value                            NaN
user_id                                   3
video_id                               4724
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 10, dtype: object
explicit = 1.0
index = 11 row = rating_date_creation    2017-12-01 23:00:00
rating_value                              1
user_id                                   3
video_id                               4726
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 11, dtype: object
explicit = nan
index = 12 row = rating_date_creation    2017-12-01 23:30:00
rating_value                            NaN
user_id                                   3
video_id                               4728
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 12, dtype: object
explicit = 1.0
index = 13 row = rating_date_creation    2017-12-05 14:30:01
rating_value                              1
user_id                                   3
video_id                               4746
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 13, dtype: object
explicit = 1.0
index = 14 row = rating_date_creation    2017-12-05 14:00:00
rating_value                              1
user_id                                   3
video_id                               4747
video_watch_time                         90
video_watched_type                 notified
rating_implicit                         0.9
rating_explicit                           1
overall_rating_value                   0.97
Name: 14, dtype: object
explicit = nan
index = 16 row = rating_date_creation    2017-12-07 05:00:00
rating_value                            NaN
user_id                                   3
video_id                               4763
video_watch_time                         33
video_watched_type                 notified
rating_implicit                        0.33
rating_explicit                         NaN
overall_rating_value                  0.165
Name: 16, dtype: object
explicit = -1.0
index = 18 row = rating_date_creation    2017-12-07 03:00:00
rating_value                             -1
user_id                                   3
video_id                               4767
video_watch_time                          6
video_watched_type                 notified
rating_implicit                        0.06
rating_explicit                          -1
overall_rating_value                 -0.718
Name: 18, dtype: object
explicit = 0.0
explicit = 1.0
index = 20 row = rating_date_creation    2017-12-22 16:12:07
rating_value                              1
user_id                                   4
video_id                               4779
video_watch_time                        100
video_watched_type                   forced
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 20, dtype: object
explicit = 1.0
index = 21 row = rating_date_creation    2017-12-22 16:09:20
rating_value                              1
user_id                                   4
video_id                               4851
video_watch_time                          7
video_watched_type                   forced
rating_implicit                        0.07
rating_explicit                           1
overall_rating_value                  0.721
Name: 21, dtype: object
explicit = 0.0
explicit = 0.0
explicit = 0.0
explicit = 0.0
explicit = 1.0
index = 28 row = rating_date_creation    2017-12-22 15:44:36
rating_value                              1
user_id                                   4
video_id                               4963
video_watch_time                          5
video_watched_type                   forced
rating_implicit                        0.05
rating_explicit                           1
overall_rating_value                  0.715
Name: 28, dtype: object
explicit = 0.0
explicit = 1.0
index = 30 row = rating_date_creation    2018-01-11 15:51:50
rating_value                              1
user_id                                   4
video_id                               5035
video_watch_time                          2
video_watched_type                   forced
rating_implicit                        0.02
rating_explicit                           1
overall_rating_value                  0.706
Name: 30, dtype: object
explicit = 0.0
explicit = 1.0
index = 32 row = rating_date_creation    2018-01-10 17:39:34
rating_value                              1
user_id                                   4
video_id                               5065
video_watch_time                          1
video_watched_type                   forced
rating_implicit                        0.01
rating_explicit                           1
overall_rating_value                  0.703
Name: 32, dtype: object
explicit = nan
index = 33 row = rating_date_creation    2018-01-10 16:35:19
rating_value                            NaN
user_id                                   4
video_id                               5068
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 33, dtype: object
explicit = -1.0
index = 36 row = rating_date_creation    2018-01-08 17:09:23
rating_value                             -1
user_id                                   4
video_id                               5160
video_watch_time                         95
video_watched_type                 notified
rating_implicit                        0.95
rating_explicit                          -1
overall_rating_value                 -0.985
Name: 36, dtype: object
explicit = 0.0
explicit = nan
index = 38 row = rating_date_creation    2018-01-10 17:03:35
rating_value                            NaN
user_id                                   4
video_id                               5186
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 38, dtype: object
explicit = 0.0
explicit = nan
index = 40 row = rating_date_creation    2018-01-10 16:58:35
rating_value                            NaN
user_id                                   4
video_id                               5188
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 40, dtype: object
explicit = nan
index = 41 row = rating_date_creation    2018-01-10 16:53:35
rating_value                            NaN
user_id                                   4
video_id                               5189
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 41, dtype: object
explicit = 0.0
explicit = nan
index = 43 row = rating_date_creation    2018-01-10 17:13:36
rating_value                            NaN
user_id                                   4
video_id                               5194
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 43, dtype: object
explicit = nan
index = 44 row = rating_date_creation    2018-01-11 17:39:31
rating_value                            NaN
user_id                                   4
video_id                               5204
video_watch_time                         76
video_watched_type                 injected
rating_implicit                        0.76
rating_explicit                         NaN
overall_rating_value                   0.38
Name: 44, dtype: object
explicit = nan
index = 45 row = rating_date_creation    2018-01-11 17:38:13
rating_value                            NaN
user_id                                   4
video_id                               5205
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 45, dtype: object
explicit = nan
index = 46 row = rating_date_creation    2017-12-04 12:06:13
rating_value                            NaN
user_id                                   6
video_id                               4736
video_watch_time                         38
video_watched_type                   forced
rating_implicit                        0.38
rating_explicit                         NaN
overall_rating_value                   0.19
Name: 46, dtype: object
explicit = 1.0
index = 47 row = rating_date_creation    2017-12-04 11:00:00
rating_value                              1
user_id                                   6
video_id                               4737
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 47, dtype: object
explicit = 0.0
explicit = -1.0
index = 49 row = rating_date_creation    2017-12-09 00:00:00
rating_value                             -1
user_id                                   7
video_id                               4672
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                          -1
overall_rating_value                     -1
Name: 49, dtype: object
explicit = 0.0
explicit = 1.0
index = 51 row = rating_date_creation    2017-12-03 21:30:00
rating_value                              1
user_id                                   7
video_id                               4721
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 51, dtype: object
explicit = nan
index = 52 row = rating_date_creation    2017-12-15 20:00:01
rating_value                            NaN
user_id                                   7
video_id                               4741
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 52, dtype: object
explicit = 0.0
explicit = nan
index = 54 row = rating_date_creation    2017-12-15 21:30:00
rating_value                            NaN
user_id                                   7
video_id                               4753
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 54, dtype: object
explicit = 1.0
index = 55 row = rating_date_creation    2017-12-10 22:30:01
rating_value                              1
user_id                                   7
video_id                               4774
video_watch_time                         69
video_watched_type                 notified
rating_implicit                        0.69
rating_explicit                           1
overall_rating_value                  0.907
Name: 55, dtype: object
explicit = 0.0
explicit = 1.0
index = 57 row = rating_date_creation    2017-12-11 23:00:00
rating_value                              1
user_id                                   7
video_id                               4809
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 57, dtype: object
explicit = nan
index = 58 row = rating_date_creation    2017-12-15 14:00:00
rating_value                            NaN
user_id                                   7
video_id                               4820
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 58, dtype: object
explicit = 0.0
explicit = 0.0
explicit = -1.0
index = 61 row = rating_date_creation    2017-12-14 23:14:13
rating_value                             -1
user_id                                   7
video_id                               4889
video_watch_time                        100
video_watched_type                   forced
rating_implicit                           1
rating_explicit                          -1
overall_rating_value                     -1
Name: 61, dtype: object
explicit = nan
index = 62 row = rating_date_creation    2017-12-15 13:00:00
rating_value                            NaN
user_id                                   7
video_id                               4890
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 62, dtype: object
explicit = nan
index = 63 row = rating_date_creation    2017-12-15 13:30:00
rating_value                            NaN
user_id                                   7
video_id                               4893
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 63, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 66 row = rating_date_creation    2017-12-16 14:00:00
rating_value                            NaN
user_id                                   7
video_id                               4898
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 66, dtype: object
explicit = nan
index = 67 row = rating_date_creation    2017-12-17 23:30:00
rating_value                            NaN
user_id                                   7
video_id                               4905
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 67, dtype: object
explicit = nan
index = 68 row = rating_date_creation    2017-12-17 23:00:00
rating_value                            NaN
user_id                                   7
video_id                               4906
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 68, dtype: object
explicit = 1.0
index = 69 row = rating_date_creation    2017-12-06 13:30:01
rating_value                              1
user_id                                   8
video_id                               4459
video_watch_time                        100
video_watched_type                 notified

index = 125 row = rating_date_creation    2017-12-28 12:15:00
rating_value                            NaN
user_id                                   8
video_id                               5030
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 125, dtype: object
explicit = nan
index = 126 row = rating_date_creation    2017-12-29 12:57:00
rating_value                            NaN
user_id                                   8
video_id                               5031
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 126, dtype: object
explicit = nan
index = 127 row = rating_date_creation    2018-01-02 12:13:00
rating_value                            NaN
user_id                                   8
video_id                               5076
video_watch_time                         14
video_watched_type                 injected
rating_implicit                        0.14
rating_explicit                         NaN
overall_rating_value                   0.07
Name: 127, dtype: object
explicit = 0.0
explicit = nan
index = 129 row = rating_date_creation    2018-01-03 12:08:00
rating_value                            NaN
user_id                                   8
video_id                               5081
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 129, dtype: object
explicit = nan
index = 130 row = rating_date_creation    2018-01-11 01:58:01
rating_value                            NaN
user_id                                   8
video_id                               5087
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 130, dtype: object
explicit = 0.0
explicit = nan
index = 132 row = rating_date_creation    2018-01-11 01:48:01
rating_value                            NaN
user_id                                   8
video_id                               5089
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 132, dtype: object
explicit = nan
index = 133 row = rating_date_creation    2018-01-11 01:38:02
rating_value                            NaN
user_id                                   8
video_id                               5090
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 133, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 136 row = rating_date_creation    2018-01-11 01:23:01
rating_value                            NaN
user_id                                   8
video_id                               5094
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 136, dtype: object
explicit = nan
index = 137 row = rating_date_creation    2018-01-11 01:18:01
rating_value                            NaN
user_id                                   8
video_id                               5095
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 137, dtype: object
explicit = nan
index = 138 row = rating_date_creation    2018-01-11 01:13:01
rating_value                            NaN
user_id                                   8
video_id                               5096
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 138, dtype: object
explicit = nan
index = 139 row = rating_date_creation    2018-01-11 01:08:01
rating_value                            NaN
user_id                                   8
video_id                               5100
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 139, dtype: object
explicit = 0.0
explicit = nan
index = 141 row = rating_date_creation    2018-01-11 00:58:01
rating_value                            NaN
user_id                                   8
video_id                               5112
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 141, dtype: object
explicit = nan
index = 142 row = rating_date_creation    2018-01-11 00:53:01
rating_value                            NaN
user_id                                   8
video_id                               5121
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 142, dtype: object
explicit = nan
index = 143 row = rating_date_creation    2018-01-11 00:43:01
rating_value                            NaN
user_id                                   8
video_id                               5122
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 143, dtype: object
explicit = nan
index = 144 row = rating_date_creation    2018-01-11 00:38:01
rating_value                            NaN
user_id                                   8
video_id                               5123
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 144, dtype: object
explicit = 0.0
explicit = nan
index = 146 row = rating_date_creation    2018-01-11 00:28:01
rating_value                            NaN
user_id                                   8
video_id                               5126
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 146, dtype: object
explicit = nan
index = 147 row = rating_date_creation    2018-01-11 00:23:01
rating_value                            NaN
user_id                                   8
video_id                               5127
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 147, dtype: object
explicit = nan
index = 148 row = rating_date_creation    2018-01-11 00:18:01
rating_value                            NaN
user_id                                   8
video_id                               5128
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 148, dtype: object
explicit = 0.0
explicit = nan
index = 150 row = rating_date_creation    2018-01-11 00:08:01
rating_value                            NaN
user_id                                   8
video_id                               5138
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 150, dtype: object
explicit = nan
index = 151 row = rating_date_creation    2018-01-10 23:58:01
rating_value                            NaN
user_id                                   8
video_id                               5139
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 151, dtype: object
explicit = nan
index = 152 row = rating_date_creation    2018-01-10 23:53:01
rating_value                            NaN
user_id                                   8
video_id                               5142
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 152, dtype: object
explicit = nan
index = 153 row = rating_date_creation    2018-01-10 23:43:01
rating_value                            NaN
user_id                                   8
video_id                               5144
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 153, dtype: object
explicit = nan
index = 154 row = rating_date_creation    2018-01-10 23:38:01
rating_value                            NaN
user_id                                   8
video_id                               5149
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 154, dtype: object
explicit = 0.0
explicit = nan
index = 156 row = rating_date_creation    2018-01-10 23:23:01
rating_value                            NaN
user_id                                   8
video_id                               5153
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 156, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 159 row = rating_date_creation    2018-01-10 23:08:01
rating_value                            NaN
user_id                                   8
video_id                               5156
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 159, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 162 row = rating_date_creation    2018-01-10 21:13:01
rating_value                            NaN
user_id                                   8
video_id                               5160
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 162, dtype: object
explicit = 0.0
explicit = nan
index = 164 row = rating_date_creation    2018-01-10 22:53:01
rating_value                            NaN
user_id                                   8
video_id                               5162
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 164, dtype: object
explicit = 0.0
explicit = nan
index = 166 row = rating_date_creation    2018-01-10 22:43:01
rating_value                            NaN
user_id                                   8
video_id                               5168
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 166, dtype: object
explicit = nan
index = 167 row = rating_date_creation    2018-01-10 21:08:01
rating_value                            NaN
user_id                                   8
video_id                               5171
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 167, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 170 row = rating_date_creation    2018-01-10 22:23:05
rating_value                            NaN
user_id                                   8
video_id                               5174
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 170, dtype: object
explicit = nan
index = 171 row = rating_date_creation    2018-01-10 22:18:01
rating_value                            NaN
user_id                                   8
video_id                               5177
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 171, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 174 row = rating_date_creation    2018-01-10 21:58:01
rating_value                            NaN
user_id                                   8
video_id                               5184
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 174, dtype: object
explicit = nan
index = 175 row = rating_date_creation    2018-01-10 21:53:01
rating_value                            NaN
user_id                                   8
video_id                               5185
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 175, dtype: object
explicit = 0.0
explicit = nan
index = 177 row = rating_date_creation    2018-01-10 21:43:01
rating_value                            NaN
user_id                                   8
video_id                               5190
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 177, dtype: object
explicit = 0.0
explicit = nan
index = 179 row = rating_date_creation    2018-01-10 21:28:01
rating_value                            NaN
user_id                                   8
video_id                               5192
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 179, dtype: object
explicit = nan
index = 180 row = rating_date_creation    2018-01-10 21:23:01
rating_value                            NaN
user_id                                   8
video_id                               5194
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 180, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 183 row = rating_date_creation    2018-01-13 14:37:35
rating_value                            NaN
user_id                                   8
video_id                               5201
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 183, dtype: object
explicit = 0.0
explicit = nan
index = 185 row = rating_date_creation    2018-01-13 14:22:35
rating_value                            NaN
user_id                                   8
video_id                               5203
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 185, dtype: object
explicit = 0.0
explicit = nan
index = 187 row = rating_date_creation    2018-01-13 13:42:53
rating_value                            NaN
user_id                                   8
video_id                               5213
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 187, dtype: object
explicit = 0.0
explicit = nan
index = 189 row = rating_date_creation    2017-12-09 18:00:00
rating_value                            NaN
user_id                                   9
video_id                               4448
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 189, dtype: object
explicit = nan
index = 190 row = rating_date_creation    2017-12-13 22:00:01
rating_value                            NaN
user_id                                   9
video_id                               4453
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 190, dtype: object
explicit = nan
index = 191 row = rating_date_creation    2017-12-09 10:30:00
rating_value                            NaN
user_id                                   9
video_id                               4454
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 191, dtype: object
explicit = 1.0
index = 192 row = rating_date_creation    2017-12-09 10:00:00
rating_value                              1
user_id                                   9
video_id                               4457
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 192, dtype: object
explicit = 0.0
explicit = nan
index = 195 row = rating_date_creation    2017-12-15 22:30:01

explicit = 1.0
index = 218 row = rating_date_creation    2017-12-12 20:46:47
rating_value                              1
user_id                                   9
video_id                               4698
video_watch_time                          4
video_watched_type                   forced
rating_implicit                        0.04
rating_explicit                           1
overall_rating_value                  0.712
Name: 218, dtype: object
explicit = 0.0
explicit = nan
index = 220 row = rating_date_creation    2017-12-23 23:00:00
rating_value                            NaN
user_id                                   9
video_id                               4701
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 220, dtype: object
explicit = 0.0
explicit = 1.0
index = 222 row = rating_date_creation    2017-12-04 08:30:00
rating_value                              1
user_id                                   9
video_id                               4738
video_watch_time                          8
video_watched_type                 notified
rating_implicit                        0.08
rating_explicit                           1
overall_rating_value                  0.724
Name: 222, dtype: object
explicit = 1.0
index = 224 row = rating_date_creation    2017-12-23 22:30:00
rating_value                              1
user_id                                   9
video_id                               4751
video_watch_time                         10
video_watched_type                 injected
rating_implicit                         0.1
rating_explicit                           1
overall_rating_value                   0.73
Name: 224, dtype: object
explicit = nan
index = 226 row = rating_date_creation    2017-12-23 21:00:00
rating_value                            NaN
user_id                                   9
video_id                               4760
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 226, dtype: object
explicit = nan
index = 227 row = rating_date_creation    2017-12-23 20:30:00
rating_value                            NaN
user_id                                   9
video_id                               4762
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 227, dtype: object
explicit = nan
index = 228 row = rating_date_creation    2017-12-23 20:00:00
rating_value                            NaN
user_id                                   9
video_id                               4764
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 228, dtype: object
explicit = 0.0
explicit = nan
index = 231 row = rating_date_creation    2017-12-08 11:30:01
rating_value                            NaN
user_id                                   9
video_id                               4770
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 231, dtype: object
explicit = 0.0
explicit = nan
index = 233 row = rating_date_creation    2017-12-10 13:30:00
rating_value                            NaN
user_id                                   9
video_id                               4775
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 233, dtype: object
explicit = 0.0
explicit = 0.0
explicit = 0.0
explicit = 0.0
explicit = 0.0
explicit = nan
index = 239 row = rating_date_creation    2017-12-08 10:00:00
rating_value                            NaN
user_id                                   9
video_id                               4784
video_watch_time                         36
video_watched_type                 injected
rating_implicit                        0.36
rating_explicit                         NaN
overall_rating_value                   0.18
Name: 239, dtype: object
explicit = 0.0
explicit = 0.0
explicit = 0.0
explicit = nan
index = 244 row = rating_date_creation    2017-12-23 19:00:00
rating_value                            NaN
user_id                                   9
video_id                               4809
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 244, dtype: object
explicit = 0.0
explicit = 1.0
index = 246 row = rating_date_creation    2017-12-13 21:30:00
rating_value                              1
user_id                                   9
video_id                               4811
video_watch_time                          1
video_watched_type                 injected
rating_implicit                        0.01
rating_explicit                           1
overall_rating_value                  0.703
Name: 246, dtype: object
explicit = nan
index = 247 row = rating_date_creation    2017-12-23 18:00:00
rating_value                            NaN
user_id                                   9
video_id                               4812
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 247, dtype: object
explicit = 0.0
explicit = nan
index = 249 row = rating_date_creation    2017-12-23 17:00:00
rating_value                            NaN
user_id                                   9
video_id                               4819
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 249, dtype: object
explicit = nan
index = 250 row = rating_date_creation    2017-12-15 08:00:01
rating_value                            NaN
user_id                                   9
video_id                               4820
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 250, dtype: object
explicit = 0.0
explicit = nan
index = 252 row = rating_date_creation    2017-12-14 13:00:01
rating_value                            NaN
user_id                                   9
video_id                               4824
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 252, dtype: object
explicit = nan
index = 253 row = rating_date_creation    2017-12-14 12:00:01
rating_value                            NaN
user_id                                   9
video_id                               4826
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 253, dtype: object
explicit = 1.0
index = 254 row = rating_date_creation    2017-12-14 11:30:01
rating_value                              1
user_id                                   9
video_id                               4827
video_watch_time                          1
video_watched_type                 injected
rating_implicit                        0.01
rating_explicit                           1
overall_rating_value                  0.703
Name: 254, dtype: object
explicit = nan
index = 255 row = rating_date_creation    2017-12-14 11:00:00
rating_value                            NaN
user_id                                   9
video_id                               4831
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 255, dtype: object
explicit = 0.0
explicit = nan
index = 257 row = rating_date_creation    2017-12-12 20:45:50
rating_value                            NaN
user_id                                   9
video_id                               4851
video_watch_time                         10
video_watched_type                   forced
rating_implicit                         0.1
rating_explicit                         NaN
overall_rating_value                   0.05
Name: 257, dtype: object
explicit = 0.0
explicit = nan
index = 261 row = rating_date_creation    2017-12-13 23:00:01
rating_value                            NaN
user_id                                   9
video_id                               4859
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 261, dtype: object
explicit = nan
index = 262 row = rating_date_creation    2017-12-13 21:00:00
rating_value                            NaN
user_id                                   9
video_id                               4860
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 262, dtype: object
explicit = nan
index = 263 row = rating_date_creation    2017-12-14 08:30:00
rating_value                            NaN
user_id                                   9
video_id                               4877
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 263, dtype: object
explicit = nan
index = 264 row = rating_date_creation    2017-12-15 01:00:01
rating_value                            NaN
user_id                                   9
video_id                               4880
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 264, dtype: object
explicit = nan
index = 265 row = rating_date_creation    2017-12-14 22:30:01
rating_value                            NaN
user_id                                   9
video_id                               4882
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 265, dtype: object
explicit = nan
index = 266 row = rating_date_creation    2017-12-14 21:30:01
rating_value                            NaN
user_id                                   9
video_id                               4883
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 266, dtype: object
explicit = 1.0
index = 267 row = rating_date_creation    2017-12-14 23:30:01
rating_value                              1
user_id                                   9
video_id                               4889
video_watch_time                          5
video_watched_type                 injected
rating_implicit                        0.05
rating_explicit                           1
overall_rating_value                  0.715
Name: 267, dtype: object
explicit = nan
index = 268 row = rating_date_creation    2017-12-15 08:30:01
rating_value                            NaN
user_id                                   9
video_id                               4890
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 268, dtype: object
explicit = nan
index = 269 row = rating_date_creation    2017-12-23 16:30:00
rating_value                            NaN
user_id                                   9
video_id                               4893
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 269, dtype: object
explicit = nan
index = 270 row = rating_date_creation    2017-12-15 21:30:01
rating_value                            NaN
user_id                                   9
video_id                               4894
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 270, dtype: object
explicit = nan
index = 271 row = rating_date_creation    2017-12-15 20:30:01
rating_value                            NaN
user_id                                   9
video_id                               4895
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 271, dtype: object
explicit = nan
index = 272 row = rating_date_creation    2017-12-23 16:00:00
rating_value                            NaN
user_id                                   9
video_id                               4898
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 272, dtype: object
explicit = nan
index = 274 row = rating_date_creation    2017-12-23 15:30:00
rating_value                            NaN
user_id                                   9
video_id                               4906
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 274, dtype: object
explicit = nan
index = 275 row = rating_date_creation    2017-12-23 15:00:00
rating_value                            NaN
user_id                                   9
video_id                               4910
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 275, dtype: object
explicit = 0.0
explicit = nan
index = 277 row = rating_date_creation    2017-12-23 14:00:00
rating_value                            NaN
user_id                                   9
video_id                               4912
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 277, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 280 row = rating_date_creation    2017-12-23 13:00:00
rating_value                            NaN
user_id                                   9
video_id                               4922
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 280, dtype: object
explicit = 0.0
explicit = 0.0
explicit = 0.0
explicit = 0.0
explicit = nan
index = 285 row = rating_date_creation    2017-12-25 10:30:00
rating_value                            NaN
user_id                                   9
video_id                               4987
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 285, dtype: object
explicit = nan
index = 286 row = rating_date_creation    2017-12-26 08:13:00
rating_value                            NaN
user_id                                   9
video_id                               4990
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 286, dtype: object
explicit = 0.0
explicit = 1.0
index = 288 row = rating_date_creation    2017-12-26 10:17:00
rating_value                              1
user_id                                   9
video_id                               4992
video_watch_time                          1
video_watched_type                 injected
rating_implicit                        0.01
rating_explicit                           1
overall_rating_value                  0.703
Name: 288, dtype: object
explicit = nan
index = 289 row = rating_date_creation    2018-01-11 00:36:02
rating_value                            NaN
user_id                                   9
video_id                               4993
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 289, dtype: object
explicit = 0.0
explicit = nan
index = 291 row = rating_date_creation    2018-01-11 00:26:02
rating_value                            NaN
user_id                                   9
video_id                               5000
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 291, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 294 row = rating_date_creation    2018-01-08 19:02:11
rating_value                            NaN
user_id                                   9
video_id                               5005
video_watch_time                         99
video_watched_type                 injected
rating_implicit                        0.99
rating_explicit                         NaN
overall_rating_value                  0.495
Name: 294, dtype: object
explicit = 0.0
explicit = 1.0
index = 296 row = rating_date_creation    2018-01-11 00:06:02
rating_value                              1
user_id                                   9
video_id                               5007
video_watch_time                         62
video_watched_type                 injected
rating_implicit                        0.62
rating_explicit                           1
overall_rating_value                  0.886
Name: 296, dtype: object
explicit = 0.0
explicit = -1.0

explicit = 0.0
explicit = nan
index = 326 row = rating_date_creation    2018-01-08 19:32:37
rating_value                            NaN
user_id                                   9
video_id                               5159
video_watch_time                         64
video_watched_type                 injected
rating_implicit                        0.64
rating_explicit                         NaN
overall_rating_value                   0.32
Name: 326, dtype: object
explicit = 0.0
explicit = nan
index = 328 row = rating_date_creation    2018-01-10 21:10:46
rating_value                            NaN
user_id                                   9
video_id                               5168
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 328, dtype: object
explicit = nan
index = 329 row = rating_date_creation    2018-01-10 21:05:46
rating_value                            NaN
user_id                                   9
video_id                               5171
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 329, dtype: object
explicit = 0.0
explicit = 0.0
explicit = 0.0
explicit = nan
index = 333 row = rating_date_creation    2018-01-10 20:40:46
rating_value                            NaN
user_id                                   9
video_id                               5184
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 333, dtype: object
explicit = 0.0
explicit = 0.0
explicit = 1.0
index = 336 row = rating_date_creation    2018-01-10 20:17:34
rating_value                              1
user_id                                   9
video_id                               5191
video_watch_time                         67
video_watched_type                 injected
rating_implicit                        0.67
rating_explicit                           1
overall_rating_value                  0.901
Name: 336, dtype: object
explicit = nan
index = 337 row = rating_date_creation    2018-01-10 20:07:34
rating_value                            NaN
user_id                                   9
video_id                               5192
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 337, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 340 row = rating_date_creation    2018-01-12 08:56:10
rating_value                            NaN
user_id                                   9
video_id                               5205
video_watch_time                         14
video_watched_type                 notified
rating_implicit                        0.14
rating_explicit                         NaN
overall_rating_value                   0.07
Name: 340, dtype: object
explicit = nan
index = 341 row = rating_date_creation    2018-01-13 00:05:57
rating_value                            NaN
user_id                                   9
video_id                               5212
video_watch_time                         24
video_watched_type                 notified
rating_implicit                        0.24
rating_explicit                         NaN
overall_rating_value                   0.12
Name: 341, dtype: object
explicit = nan
index = 344 row = rating_date_creation    2018-01-12 23:50:57
rating_value                            NaN
user_id                                   9
video_id                               5217
video_watch_time                         12
video_watched_type                 notified
rating_implicit                        0.12
rating_explicit                         NaN
overall_rating_value                   0.06
Name: 344, dtype: object
explicit = nan
index = 345 row = rating_date_creation    2018-01-13 20:21:59
rating_value                            NaN
user_id                                   9
video_id                               5225
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 345, dtype: object
explicit = nan
index = 346 row = rating_date_creation    2018-01-14 20:25:35
rating_value                            NaN
user_id                                   9
video_id                               5229
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 346, dtype: object
explicit = 1.0
index = 347 row = rating_date_creation    2017-12-15 21:30:01
rating_value                              1
user_id                                  18
video_id                               4618
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 347, dtype: object
explicit = -1.0
index = 348 row = rating_date_creation    2017-12-11 08:30:01
rating_value                             -1
user_id                                  18
video_id                               4622
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                          -1
overall_rating_value                     -1
Name: 348, dtype: object
explicit = 1.0
index = 349 row = rating_date_creation    2017-12-17 21:30:01
rating_value                              1
user_id                                  18
video_id                               4626
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 349, dtype: object
explicit = 1.0
index = 350 row = rating_date_creation    2017-12-18 14:30:01
rating_value                              1
user_id                                  18
video_id                               4639
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 350, dtype: object
explicit = nan
index = 351 row = rating_date_creation    2017-12-14 09:00:01
rating_value                            NaN
user_id                                  18
video_id                               4655
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 351, dtype: object
explicit = 1.0
index = 352 row = rating_date_creation    2017-12-14 12:30:01
rating_value                              1
user_id                                  18
video_id                               4687
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 352, dtype: object
explicit = nan
index = 353 row = rating_date_creation    2017-12-14 18:00:01
rating_value                            NaN
user_id                                  18
video_id                               4703
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 353, dtype: object
explicit = 1.0
index = 354 row = rating_date_creation    2017-12-07 12:29:47
rating_value                              1
user_id                                  18
video_id                               4709
video_watch_time                          5
video_watched_type                   forced
rating_implicit                        0.05
rating_explicit                           1
overall_rating_value                  0.715
Name: 354, dtype: object
explicit = nan
index = 355 row = rating_date_creation    2017-12-19 10:30:00
rating_value                            NaN
user_id                                  18
video_id                               4711
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 355, dtype: object
explicit = 1.0
index = 356 row = rating_date_creation    2017-12-21 10:00:00
rating_value                              1
user_id                                  18
video_id                               4743
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 356, dtype: object
explicit = 1.0
index = 357 row = rating_date_creation    2017-12-14 22:00:01
rating_value                              1
user_id                                  18
video_id                               4744
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 357, dtype: object
explicit = nan
index = 358 row = rating_date_creation    2017-12-21 09:00:00
rating_value                            NaN
user_id                                  18
video_id                               4747
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 358, dtype: object
explicit = nan
index = 359 row = rating_date_creation    2017-12-19 09:00:00
rating_value                            NaN
user_id                                  18
video_id                               4748
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 359, dtype: object
explicit = nan
index = 360 row = rating_date_creation    2017-12-08 10:30:01
rating_value                            NaN
user_id                                  18
video_id                               4752
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 360, dtype: object
explicit = nan
index = 361 row = rating_date_creation    2017-12-11 13:00:01
rating_value                            NaN
user_id                                  18
video_id                               4753
video_watch_time                         60
video_watched_type                 notified
rating_implicit                         0.6
rating_explicit                         NaN
overall_rating_value                    0.3
Name: 361, dtype: object
explicit = nan
index = 362 row = rating_date_creation    2017-12-07 12:22:05
rating_value                            NaN
user_id                                  18
video_id                               4765
video_watch_time                         55
video_watched_type                   forced
rating_implicit                        0.55
rating_explicit                         NaN
overall_rating_value                  0.275
Name: 362, dtype: object
explicit = nan
index = 363 row = rating_date_creation    2017-12-07 12:19:56
rating_value                            NaN
user_id                                  18
video_id                               4768
video_watch_time                         35
video_watched_type                   forced
rating_implicit                        0.35
rating_explicit                         NaN
overall_rating_value                  0.175
Name: 363, dtype: object
explicit = 1.0
index = 364 row = rating_date_creation    2017-12-07 13:30:01
rating_value                              1
user_id                                  18
video_id                               4770
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 364, dtype: object
explicit = nan
index = 365 row = rating_date_creation    2017-12-10 21:00:00
rating_value                            NaN
user_id                                  18
video_id                               4775
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 365, dtype: object
explicit = nan
index = 366 row = rating_date_creation    2017-12-10 20:30:01
rating_value                            NaN
user_id                                  18
video_id                               4776
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 366, dtype: object
explicit = nan
index = 367 row = rating_date_creation    2017-12-10 19:30:00
rating_value                            NaN
user_id                                  18
video_id                               4778
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 367, dtype: object
explicit = 1.0
index = 368 row = rating_date_creation    2017-12-10 15:00:01
rating_value                              1
user_id                                  18
video_id                               4779
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 368, dtype: object
explicit = nan
index = 369 row = rating_date_creation    2017-12-10 10:00:00
rating_value                            NaN
user_id                                  18
video_id                               4782
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 369, dtype: object
explicit = 1.0
index = 370 row = rating_date_creation    2017-12-09 19:30:01
rating_value                              1
user_id                                  18
video_id                               4783
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 370, dtype: object
explicit = nan
index = 371 row = rating_date_creation    2017-12-08 10:00:01
rating_value                            NaN
user_id                                  18
video_id                               4784
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 371, dtype: object
explicit = nan
index = 372 row = rating_date_creation    2017-12-10 09:30:01
rating_value                            NaN
user_id                                  18
video_id                               4785
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 372, dtype: object
explicit = 0.0
explicit = nan
index = 374 row = rating_date_creation    2017-12-09 11:00:01
rating_value                            NaN
user_id                                  18
video_id                               4791
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 374, dtype: object
explicit = 1.0
index = 377 row = rating_date_creation    2017-12-12 23:30:00
rating_value                              1
user_id                                  18
video_id                               4812
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 377, dtype: object
explicit = 1.0
index = 378 row = rating_date_creation    2017-12-12 00:00:00
rating_value                              1
user_id                                  18
video_id                               4813
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 378, dtype: object
explicit = nan
index = 379 row = rating_date_creation    2017-12-18 21:30:01
rating_value                            NaN
user_id                                  18
video_id                               4819
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 379, dtype: object
explicit = 1.0
index = 380 row = rating_date_creation    2017-12-18 21:00:01
rating_value                              1
user_id                                  18
video_id                               4820
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 380, dtype: object
explicit = 1.0
index = 381 row = rating_date_creation    2017-12-13 23:30:01
rating_value                              1
user_id                                  18
video_id                               4823
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 381, dtype: object
explicit = 1.0
index = 386 row = rating_date_creation    2017-12-12 23:00:00
rating_value                              1
user_id                                  18
video_id                               4831
video_watch_time                          1
video_watched_type                 notified

index = 396 row = rating_date_creation    2017-12-17 21:00:00
rating_value                              1
user_id                                  18
video_id                               4879
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 396, dtype: object
explicit = 1.0
index = 397 row = rating_date_creation    2017-12-17 20:30:01
rating_value                              1
user_id                                  18
video_id                               4880
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 397, dtype: object
explicit = 1.0
index = 398 row = rating_date_creation    2017-12-15 22:30:01
rating_value                              1
user_id                                  18
video_id                               4881
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 398, dtype: object
explicit = nan
index = 399 row = rating_date_creation    2017-12-14 21:30:01
rating_value                            NaN
user_id                                  18
video_id                               4882
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 399, dtype: object
explicit = nan
index = 400 row = rating_date_creation    2017-12-14 19:00:01
rating_value                            NaN
user_id                                  18
video_id                               4883
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 400, dtype: object
explicit = 1.0
index = 401 row = rating_date_creation    2017-12-15 22:00:01
rating_value                              1
user_id                                  18
video_id                               4889
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 401, dtype: object
explicit = 1.0
index = 402 row = rating_date_creation    2017-12-15 09:00:01
rating_value                              1
user_id                                  18
video_id                               4890
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 402, dtype: object
explicit = 1.0
index = 403 row = rating_date_creation    2017-12-15 21:00:01
rating_value                              1
user_id                                  18
video_id                               4893
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 403, dtype: object
explicit = 1.0
index = 404 row = rating_date_creation    2017-12-15 20:30:01
rating_value                              1
user_id                                  18
video_id                               4894
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 404, dtype: object
explicit = nan
index = 405 row = rating_date_creation    2017-12-15 20:00:01
rating_value                            NaN
user_id                                  18
video_id                               4895
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 405, dtype: object
explicit = nan
index = 406 row = rating_date_creation    2017-12-17 19:30:01
rating_value                            NaN
user_id                                  18
video_id                               4898
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 406, dtype: object
explicit = 1.0
index = 407 row = rating_date_creation    2017-12-17 19:00:00
rating_value                              1
user_id                                  18
video_id                               4905
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 407, dtype: object
explicit = 0.0
explicit = nan
index = 409 row = rating_date_creation    2017-12-18 13:00:01
rating_value                            NaN
user_id                                  18
video_id                               4910
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 409, dtype: object
explicit = 1.0
index = 410 row = rating_date_creation    2017-12-18 13:30:00
rating_value                              1
user_id                                  18
video_id                               4911
video_watch_time                          4
video_watched_type                 injected
rating_implicit                        0.04
rating_explicit                           1
overall_rating_value                  0.712
Name: 410, dtype: object
explicit = 1.0
index = 411 row = rating_date_creation    2017-12-18 19:00:01
rating_value                              1
user_id                                  18
video_id                               4912
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 411, dtype: object
explicit = nan
index = 412 row = rating_date_creation    2017-12-19 08:30:00
rating_value                            NaN
user_id                                  18
video_id                               4917
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 412, dtype: object
explicit = 1.0
index = 413 row = rating_date_creation    2017-12-19 11:00:00
rating_value                              1
user_id                                  18
video_id                               4919
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 413, dtype: object
explicit = nan
index = 414 row = rating_date_creation    2017-12-19 19:00:00
rating_value                            NaN
user_id                                  18
video_id                               4922
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 414, dtype: object
explicit = nan
index = 416 row = rating_date_creation    2017-12-19 22:00:00
rating_value                            NaN
user_id                                  18
video_id                               4926
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 416, dtype: object
explicit = nan
index = 418 row = rating_date_creation    2017-12-20 11:00:00
rating_value                            NaN
user_id                                  18
video_id                               4934
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 418, dtype: object
explicit = 1.0
index = 419 row = rating_date_creation    2017-12-20 09:00:01
rating_value                              1
user_id                                  18
video_id                               4935
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 419, dtype: object
explicit = nan
index = 420 row = rating_date_creation    2017-12-20 23:30:00
rating_value                            NaN
user_id                                  18
video_id                               4937
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 420, dtype: object
explicit = 0.0
explicit = 1.0
index = 422 row = rating_date_creation    2017-12-20 16:00:00
rating_value                              1
user_id                                  18
video_id                               4939
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 422, dtype: object
explicit = nan
index = 424 row = rating_date_creation    2017-12-20 22:30:00
rating_value                            NaN
user_id                                  18
video_id                               4942
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 424, dtype: object
explicit = nan
index = 425 row = rating_date_creation    2017-12-20 22:00:00
rating_value                            NaN
user_id                                  18
video_id                               4943
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 425, dtype: object
explicit = 0.0
explicit = nan
index = 427 row = rating_date_creation    2017-12-20 21:30:00
rating_value                            NaN
user_id                                  18
video_id                               4945
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 427, dtype: object
explicit = nan
index = 428 row = rating_date_creation    2017-12-20 21:00:00
rating_value                            NaN
user_id                                  18
video_id                               4946
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 428, dtype: object
explicit = nan
index = 429 row = rating_date_creation    2017-12-21 08:30:00
rating_value                            NaN
user_id                                  18
video_id                               4950
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 429, dtype: object
explicit = nan
index = 430 row = rating_date_creation    2017-12-21 10:30:00
rating_value                            NaN
user_id                                  18
video_id                               4951
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 430, dtype: object
explicit = nan
index = 431 row = rating_date_creation    2017-12-13 12:00:00
rating_value                            NaN
user_id                                  20
video_id                               4615
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 431, dtype: object
explicit = 0.0
explicit = 1.0
index = 433 row = rating_date_creation    2017-12-05 20:30:01
rating_value                              1
user_id                                  20
video_id                               4672
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 433, dtype: object
explicit = 0.0
explicit = -1.0
index = 435 row = rating_date_creation    2017-12-05 23:00:01
rating_value                             -1
user_id                                  20
video_id                               4752
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                          -1
overall_rating_value                     -1
Name: 435, dtype: object
explicit = nan
index = 436 row = rating_date_creation    2017-12-05 22:30:01
rating_value                            NaN
user_id                                  20
video_id                               4753
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 436, dtype: object
explicit = 0.0
explicit = 0.0
explicit = 1.0
index = 439 row = rating_date_creation    2017-12-06 21:30:00
rating_value                              1
user_id                                  20
video_id                               4765
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 439, dtype: object
explicit = nan
index = 440 row = rating_date_creation    2017-12-13 11:00:01
rating_value                            NaN
user_id                                  20
video_id                               4770
video_watch_time                         31
video_watched_type                 notified
rating_implicit                        0.31
rating_explicit                         NaN
overall_rating_value                  0.155
Name: 440, dtype: object
explicit = 0.0
explicit = 1.0
index = 442 row = rating_date_creation    2017-12-13 11:07:19
rating_value                              1
user_id                                  20
video_id                               4789
video_watch_time                         39
video_watched_type                   forced
rating_implicit                        0.39
rating_explicit                           1
overall_rating_value                  0.817
Name: 442, dtype: object
explicit = 1.0
index = 443 row = rating_date_creation    2017-12-10 17:30:01
rating_value                              1
user_id                                  20
video_id                               4791
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 443, dtype: object
explicit = 0.0
explicit = nan
index = 445 row = rating_date_creation    2017-12-15 21:30:01
rating_value                            NaN
user_id                                  20
video_id                               4827
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 445, dtype: object
explicit = nan
index = 446 row = rating_date_creation    2018-01-11 17:42:26
rating_value                            NaN
user_id                                  20
video_id                               4852
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 446, dtype: object
explicit = nan
index = 447 row = rating_date_creation    2017-12-15 21:00:01
rating_value                            NaN
user_id                                  20
video_id                               4893
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 447, dtype: object
explicit = 1.0
index = 448 row = rating_date_creation    2017-12-15 23:00:01
rating_value                              1
user_id                                  20
video_id                               4895
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 448, dtype: object
explicit = nan
index = 449 row = rating_date_creation    2018-01-11 17:41:23
rating_value                            NaN
user_id                                  20
video_id                               4973
video_watch_time                         32
video_watched_type                 injected
rating_implicit                        0.32
rating_explicit                         NaN
overall_rating_value                   0.16
Name: 449, dtype: object
explicit = -1.0
index = 450 row = rating_date_creation    2018-01-08 17:08:36
rating_value                             -1
user_id                                  20
video_id                               5089
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                          -1
overall_rating_value                     -1
Name: 450, dtype: object
explicit = 0.0
explicit = nan
index = 454 row = rating_date_creation    2018-01-08 17:13:36
rating_value                            NaN
user_id                                  20
video_id                               5162
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1

In [8]:
# read CSV using a relative path
import pandas as pd
import requests
URL='http://api_mysql.tv4e.pt/api/recommendations/videos'
data= requests.get(URL)
df=pd.DataFrame(data.json())

In [15]:
df[df['video_location'] == '3'].shape

KeyError: 'video_location'

In [ ]:
df.video_location.unique()

In [ ]:
from dateutil import parser
pd.to_datetime(df.video_date_creation)
df=df.sort_values(['video_date_creation'])

datett = df[(df['video_id'] == 4402)].video_date_creation[0]
parser.parse(datett)

# n_recommendations=5
# filtered_recommendations = {video_id: "" for video_id in df[:-n_recommendations-1:-1].video_id}
# filtered_recommendations

In [ ]:
recs = [(video.video_id, video.video_date_creation, "")
                                        for index,video in df[:-5:-1].iterrows()]
recs

In [ ]:
import datetime
now = datetime.datetime.now()
for index,row in df[:-5:-1].iterrows():
    date = parser.parse(row.video_date_creation)
    diff = now-date
    print(diff)

In [ ]:
import dateutil
# read CSV using a relative path
import pandas as pd
import requests
URL='http://api_mysql.tv4e.pt/api/recommendations/videos'
data= requests.get(URL)
df=pd.DataFrame(data.json())
df = df.transpose()
for index, row in df.iterrows():
    print("\n")
    print(row.video_id)
    print(row.video_title)
    print(row.video_desc)
    print(dateutil.parser.parse(row.video_date_creation))
    print(row.video_location)
    print(row.video_asgie_id)
    print(row.video_asgie_title_pt)