In [1]:
# read CSV using a relative path
import pandas as pd
import requests
URL='http://api_mysql.tv4e.pt/api/recommendations/users'
data= requests.get(URL)
df=pd.DataFrame(data.json())

In [2]:
df.head()

,city_id,user_age,user_coordinates,user_gender,user_id,user_name
0,3,74,"40.6311386,-8.6574267",M,1,Dev
1,3,85,XXX,M,2,XXX
2,5,80,"40.4796835,-8.4561561",M,3,David Campelo
3,5,65,"40.629803,-8.608807",M,4,Francisco Silva
4,5,58,"40.6023542,-8.5682549",M,6,Sir Ian

In [3]:
df.city_id.unique()

array([ 3,  5, 12,  2])

In [4]:
# read CSV using a relative path
import pandas as pd
import requests
URL='http://api_mysql.tv4e.pt/api/recommendations/ratings'
data= requests.get(URL)
df=pd.DataFrame(data.json())

In [5]:
df

,rating_date_creation,rating_value,user_id,video_id,video_watch_time,video_watched_type
0,2018-01-11 12:01:31,0.0,1,4905,1,forced
1,2018-01-11 12:01:23,1.0,1,4931,1,forced
2,2018-01-11 12:00:12,0.0,1,4943,3,forced
3,2018-01-11 12:00:06,NaN,1,4980,1,forced
4,2018-01-11 12:00:02,NaN,1,4981,1,forced
5,2018-01-11 11:59:57,NaN,1,4987,1,forced
6,2018-01-11 11:59:40,NaN,1,4990,1,forced
7,2018-01-11 11:58:16,0.0,1,5000,1,forced
8,2018-01-11 11:56:04,1.0,1,5002,1,forced
9,2018-01-11 11:54:48,1.0,1,5004,2,forced
10,2018-01-11 11:54:42,NaN,1,5035,1,forced
11,2018-01-11 11:54:38,NaN,1,5154,5,forced
12,2018-01-10 15:10:35,0.0,1,5162,100,injected
13,2018-01-10 10:38:25,NaN,1,5168,100,injected
14,2018-01-10 10:30:44,NaN,1,5171,100,injected
15,2018-01-10 17:33:05,0.0,1,5183,2,forced
16,2018-01-10 15:36:15,NaN,1,5186,100,injected
17,2017-12-07 02:30:00,1.0,3,4448,87,notified
18,2017-12-06 22:00:01,-1.0,3,4576,100,notified
19,2017-12-07 02:00:00,1.0,3,4617,23,notified
20,2017-12-06 23:00:04,NaN,3,4674,100,notified
21,2017-12-06 23:30:01,-1.0,3,4699,100,notified
22,2017-12-05 11:00:00,0.0,3,4700,8,notified
23,2017-12-06 22:30:01,NaN,3,4706,55,notified
24,2017-12-02 05:00:00,NaN,3,4720,40,notified
25,2017-12-02 03:30:00,NaN,3,4724,100,notified
26,2017-12-01 23:00:00,1.0,3,4726,100,notified
27,2017-12-01 23:30:00,NaN,3,4728,100,notified
28,2017-12-05 14:30:01,1.0,3,4746,100,notified
29,2017-12-05 14:00:00,1.0,3,4747,90,notified
...,...,...,...,...,...,...
455,2017-12-12 09:00:01,0.0,23,4811,90,notified
456,2017-12-14 16:00:01,0.0,23,4880,100,notified
457,2017-12-13 19:30:00,0.0,24,4861,100,injected
458,2017-12-16 10:30:00,NaN,24,4891,100,injected
459,2017-12-18 21:30:01,NaN,24,4907,100,injected
460,2017-12-18 18:22:16,0.0,24,4908,100,forced
461,2017-12-18 21:00:01,0.0,24,4909,100,injected
462,2017-12-18 20:00:01,0.0,24,4910,100,injected
463,2017-12-18 19:30:01,NaN,24,4911,100,injected
464,2017-12-18 19:00:01,NaN,24,4912,100,injected
465,2017-12-18 18:30:01,NaN,24,4913,100,injected
466,2017-12-18 20:30:01,0.0,24,4914,100,injected
467,2017-12-19 05:30:00,NaN,24,4916,100,injected
468,2017-12-19 22:00:01,NaN,24,4922,100,injected
469,2017-12-20 18:33:11,NaN,24,4939,93,forced
470,2017-12-20 18:40:40,0.0,24,4943,100,forced
471,2017-12-21 16:30:00,NaN,24,4956,1,notified
472,2017-12-10 15:30:00,NaN,25,4710,1,notified
473,2017-12-10 15:00:00,1.0,25,4712,100,notified
474,2017-12-06 08:30:00,0.0,25,4747,100,notified
475,2017-12-05 10:00:00,0.0,25,4751,100,notified
476,2017-12-05 09:30:00,NaN,25,4752,15,notified
477,2017-12-12 17:00:00,NaN,25,4825,100,notified
478,2017-12-12 07:00:00,1.0,25,4827,84,notified
479,2017-12-12 17:30:00,NaN,25,4831,2,notified
480,2017-12-17 14:00:00,0.0,25,4893,100,injected
481,2017-12-17 15:00:00,0.0,25,4905,1,injected
482,2017-12-17 14:30:01,NaN,25,4906,100,injected
483,2017-12-18 17:30:00,NaN,25,4910,100,injected
484,2017-12-18 17:00:00,0.0,25,4911,100,injected

In [41]:
# read CSV using a relative path
import pandas as pd
import requests
URL='http://api_mysql.tv4e.pt/api/recommendations/ratings'
data= requests.get(URL)
df=pd.DataFrame(data.json())

# XXX use a function to calculate implicit rating considering the video lead time
df['rating_implicit'] = (df['video_watch_time']/100) * 0.3
df['rating_explicit'] = (df['rating_value'])         * 0.7
# If the explicit rating was negative, the implicit will be negative
df['rating_implicit'][df.rating_explicit < 0] = df['rating_implicit'] * -1
# create a new column to put implicit or explicit rating rating_value
df['overall_rating_value'] = df['rating_implicit'] + df['rating_explicit']

# implicit rating is the watched time / explicit rating is the like-0-dislike
df['rating_implicit'] = df['video_watch_time']/100
df['rating_explicit'] = df['rating_value']
df['overall_rating_value']=df['overall_rating_value'].fillna(0)

df.loc[(df['overall_rating_value'] == 0) & (df['video_watch_time'] > 25),'overall_rating_value'] = (df['video_watch_time']/100) * 0.5
#df = df[(df.video_watched_type != 'forced')]
import datetime
NOW = datetime.datetime.now()
df['rating_date_diff'] = NOW - pd.to_datetime(df['rating_date_creation'])
df = df[(df.rating_date_diff.dt.days < 14)]
#df = df[(df.overall_rating_value > 0)]
df.shape

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

(143, 10)

In [7]:
import numpy as np
for index, row in df.iterrows():
    print("explicit = {}".format(row.rating_explicit))
    if row.rating_explicit:
        print("index = {} row = {}".format(index,row))

explicit = 0.0
explicit = nan
index = 13 row = rating_date_creation    2018-01-10 10:38:25
rating_value                            NaN
user_id                                   1
video_id                               5168
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 13, dtype: object
explicit = nan
index = 14 row = rating_date_creation    2018-01-10 10:30:44
rating_value                            NaN
user_id                                   1
video_id                               5171
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 14, dtype: object
explicit = nan
index = 16 row = rating_date_creation    2018-01-10 15:36:15
rating_value                            NaN
user_id                                   1
video_id                               5186
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 16, dtype: object
explicit = 1.0
index = 17 row = rating_date_creation    2017-12-07 02:30:00
rating_value                              1
user_id                                   3
video_id                               4448
video_watch_time                         87
video_watched_type                 notified
rating_implicit                        0.87
rating_explicit                           1
overall_rating_value                  0.961
Name: 17, dtype: object
explicit = -1.0
index = 18 row = rating_date_creation    2017-12-06 22:00:01
rating_value                             -1
user_id                                   3
video_id                               4576
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                          -1
overall_rating_value                     -1
Name: 18, dtype: object
explicit = 1.0
index = 19 row = rating_date_creation    2017-12-07 02:00:00
rating_value                              1
user_id                                   3
video_id                               4617
video_watch_time                         23
video_watched_type                 notified
rating_implicit                        0.23
rating_explicit                           1
overall_rating_value                  0.769
Name: 19, dtype: object
explicit = nan
index = 20 row = rating_date_creation    2017-12-06 23:00:04
rating_value                            NaN
user_id                                   3
video_id                               4674
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 20, dtype: object
explicit = -1.0
index = 21 row = rating_date_creation    2017-12-06 23:30:01
rating_value                             -1
user_id                                   3
video_id                               4699
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                          -1
overall_rating_value                     -1
Name: 21, dtype: object
explicit = 0.0
explicit = nan
index = 23 row = rating_date_creation    2017-12-06 22:30:01
rating_value                            NaN
user_id                                   3
video_id                               4706
video_watch_time                         55
video_watched_type                 notified
rating_implicit                        0.55
rating_explicit                         NaN
overall_rating_value                  0.275
Name: 23, dtype: object
explicit = nan
index = 24 row = rating_date_creation    2017-12-02 05:00:00
rating_value                            NaN
user_id                                   3
video_id                               4720
video_watch_time                         40
video_watched_type                 notified
rating_implicit                         0.4
rating_explicit                         NaN
overall_rating_value                    0.2
Name: 24, dtype: object
explicit = nan
index = 25 row = rating_date_creation    2017-12-02 03:30:00
rating_value                            NaN
user_id                                   3
video_id                               4724
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 25, dtype: object
explicit = 1.0
index = 26 row = rating_date_creation    2017-12-01 23:00:00
rating_value                              1
user_id                                   3
video_id                               4726
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 26, dtype: object
explicit = nan
index = 27 row = rating_date_creation    2017-12-01 23:30:00
rating_value                            NaN
user_id                                   3
video_id                               4728
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 27, dtype: object
explicit = 1.0
index = 28 row = rating_date_creation    2017-12-05 14:30:01
rating_value                              1
user_id                                   3
video_id                               4746
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 28, dtype: object
explicit = 1.0
index = 29 row = rating_date_creation    2017-12-05 14:00:00
rating_value                              1
user_id                                   3
video_id                               4747
video_watch_time                         90
video_watched_type                 notified
rating_implicit                         0.9
rating_explicit                           1
overall_rating_value                   0.97
Name: 29, dtype: object
explicit = nan
index = 30 row = rating_date_creation    2017-12-05 12:00:00
rating_value                            NaN
user_id                                   3
video_id                               4749
video_watch_time                          9
video_watched_type                 notified
rating_implicit                        0.09
rating_explicit                         NaN
overall_rating_value                      0
Name: 30, dtype: object
explicit = nan
index = 31 row = rating_date_creation    2017-12-07 05:00:00
rating_value                            NaN
user_id                                   3
video_id                               4763
video_watch_time                         33
video_watched_type                 notified
rating_implicit                        0.33
rating_explicit                         NaN
overall_rating_value                  0.165
Name: 31, dtype: object
explicit = 0.0
explicit = -1.0
index = 33 row = rating_date_creation    2017-12-07 03:00:00
rating_value                             -1
user_id                                   3
video_id                               4767
video_watch_time                          6
video_watched_type                 notified
rating_implicit                        0.06
rating_explicit                          -1
overall_rating_value                 -0.718
Name: 33, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 47 row = rating_date_creation    2018-01-10 16:35:19
rating_value                            NaN
user_id                                   4
video_id                               5068
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 47, dtype: object
explicit = 0.0
explicit = -1.0
index = 50 row = rating_date_creation    2018-01-08 17:09:23
rating_value                             -1
user_id                                   4
video_id                               5160
video_watch_time                         95
video_watched_type                 notified
rating_implicit                        0.95
rating_explicit                          -1
overall_rating_value                 -0.985
Name: 50, dtype: object
explicit = 0.0
explicit = nan
index = 52 row = rating_date_creation    2018-01-10 17:03:35
rating_value                            NaN
user_id                                   4
video_id                               5186
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 52, dtype: object
explicit = 0.0
explicit = nan
index = 54 row = rating_date_creation    2018-01-10 16:58:35
rating_value                            NaN
user_id                                   4
video_id                               5188
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 54, dtype: object
explicit = nan
index = 55 row = rating_date_creation    2018-01-10 16:53:35
rating_value                            NaN
user_id                                   4
video_id                               5189
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 55, dtype: object
explicit = 0.0
explicit = nan
index = 57 row = rating_date_creation    2018-01-10 17:13:36
rating_value                            NaN
user_id                                   4
video_id                               5194
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 57, dtype: object
explicit = 1.0
index = 59 row = rating_date_creation    2017-12-04 11:00:00
rating_value                              1
user_id                                   6
video_id                               4737
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 59, dtype: object
explicit = 0.0
explicit = -1.0
index = 61 row = rating_date_creation    2017-12-09 00:00:00
rating_value                             -1
user_id                                   7
video_id                               4672
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                          -1
overall_rating_value                     -1
Name: 61, dtype: object
explicit = 0.0
explicit = 1.0
index = 63 row = rating_date_creation    2017-12-03 21:30:00
rating_value                              1
user_id                                   7
video_id                               4721
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 63, dtype: object
explicit = nan
index = 64 row = rating_date_creation    2017-12-15 20:00:01
rating_value                            NaN
user_id                                   7
video_id                               4741
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 64, dtype: object
explicit = 0.0
explicit = nan
index = 66 row = rating_date_creation    2017-12-15 21:30:00
rating_value                            NaN
user_id                                   7
video_id                               4753
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 66, dtype: object
explicit = 1.0
index = 67 row = rating_date_creation    2017-12-10 22:30:01
rating_value                              1
user_id                                   7
video_id                               4774
video_watch_time                         69
video_watched_type                 notified
rating_implicit                        0.69
rating_explicit                           1
overall_rating_value                  0.907
Name: 67, dtype: object
explicit = 0.0
explicit = 1.0
index = 69 row = rating_date_creation    2017-12-11 23:00:00
rating_value                              1
user_id                                   7
video_id                               4809
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 69, dtype: object
explicit = nan
index = 70 row = rating_date_creation    2017-12-15 14:00:00
rating_value                            NaN
user_id                                   7
video_id                               4820
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 70, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 74 row = rating_date_creation    2017-12-15 13:00:00
rating_value                            NaN
user_id                                   7
video_id                               4890
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 74, dtype: object
explicit = nan
index = 75 row = rating_date_creation    2017-12-15 13:30:00
rating_value                            NaN
user_id                                   7
video_id                               4893
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 75, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 78 row = rating_date_creation    2017-12-16 14:00:00
rating_value                            NaN
user_id                                   7
video_id                               4898
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 78, dtype: object
explicit = nan
index = 79 row = rating_date_creation    2017-12-17 23:30:00
rating_value                            NaN
user_id                                   7
video_id                               4905
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 79, dtype: object
explicit = nan
index = 80 row = rating_date_creation    2017-12-17 23:00:00
rating_value                            NaN
user_id                                   7
video_id                               4906
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 80, dtype: object
explicit = 1.0
index = 81 row = rating_date_creation    2017-12-06 13:30:01
rating_value                              1
user_id                                   8
video_id                               4459
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 81, dtype: object
explicit = 0.0
explicit = 1.0
index = 83 row = rating_date_creation    2017-12-03 16:30:00
rating_value                              1
user_id                                   8
video_id                               4549
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 83, dtype: object
explicit = nan
index = 84 row = rating_date_creation    2017-12-04 12:30:01
rating_value                            NaN
user_id                                   8
video_id                               4554
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 84, dtype: object
explicit = nan
index = 85 row = rating_date_creation    2017-12-16 15:00:01
rating_value                            NaN
user_id                                   8
video_id                               4563
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 85, dtype: object
explicit = nan
index = 86 row = rating_date_creation    2017-12-02 16:30:00
rating_value                            NaN
user_id                                   8
video_id                               4574
video_watch_time                         29
video_watched_type                 notified
rating_implicit                        0.29
rating_explicit                         NaN
overall_rating_value                  0.145
Name: 86, dtype: object
explicit = 0.0
explicit = 1.0
index = 88 row = rating_date_creation    2017-12-06 14:00:01
rating_value                              1
user_id                                   8
video_id                               4704
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 88, dtype: object
explicit = 1.0
index = 89 row = rating_date_creation    2017-12-02 16:00:00
rating_value                              1
user_id                                   8
video_id                               4714
video_watch_time                         22

explicit = 0.0
explicit = nan
index = 141 row = rating_date_creation    2018-01-03 12:08:00
rating_value                            NaN
user_id                                   8
video_id                               5081
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 141, dtype: object
explicit = nan
index = 142 row = rating_date_creation    2018-01-11 01:58:01
rating_value                            NaN
user_id                                   8
video_id                               5087
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 142, dtype: object
explicit = 0.0
explicit = nan
index = 144 row = rating_date_creation    2018-01-11 01:48:01
rating_value                            NaN
user_id                                   8
video_id                               5089
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 144, dtype: object
explicit = nan
index = 145 row = rating_date_creation    2018-01-11 01:38:02
rating_value                            NaN
user_id                                   8
video_id                               5090
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 145, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 148 row = rating_date_creation    2018-01-11 01:23:01
rating_value                            NaN
user_id                                   8
video_id                               5094
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 148, dtype: object
explicit = nan
index = 149 row = rating_date_creation    2018-01-11 01:18:01
rating_value                            NaN
user_id                                   8
video_id                               5095
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 149, dtype: object
explicit = nan
index = 150 row = rating_date_creation    2018-01-11 01:13:01
rating_value                            NaN
user_id                                   8
video_id                               5096
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 150, dtype: object
explicit = nan
index = 151 row = rating_date_creation    2018-01-11 01:08:01
rating_value                            NaN
user_id                                   8
video_id                               5100
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 151, dtype: object
explicit = 0.0
explicit = nan
index = 153 row = rating_date_creation    2018-01-11 00:58:01
rating_value                            NaN
user_id                                   8
video_id                               5112
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 153, dtype: object
explicit = nan
index = 154 row = rating_date_creation    2018-01-11 00:53:01
rating_value                            NaN
user_id                                   8
video_id                               5121
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 154, dtype: object
explicit = nan
index = 155 row = rating_date_creation    2018-01-11 00:43:01
rating_value                            NaN
user_id                                   8
video_id                               5122
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 155, dtype: object
explicit = nan
index = 156 row = rating_date_creation    2018-01-11 00:38:01
rating_value                            NaN
user_id                                   8
video_id                               5123
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 156, dtype: object
explicit = 0.0
explicit = nan
index = 158 row = rating_date_creation    2018-01-11 00:28:01
rating_value                            NaN
user_id                                   8
video_id                               5126
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 158, dtype: object
explicit = nan
index = 159 row = rating_date_creation    2018-01-11 00:23:01
rating_value                            NaN
user_id                                   8
video_id                               5127
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 159, dtype: object
explicit = nan
index = 160 row = rating_date_creation    2018-01-11 00:18:01
rating_value                            NaN
user_id                                   8
video_id                               5128
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 160, dtype: object
explicit = 0.0
explicit = nan
index = 162 row = rating_date_creation    2018-01-11 00:08:01
rating_value                            NaN
user_id                                   8
video_id                               5138
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 162, dtype: object
explicit = nan
index = 163 row = rating_date_creation    2018-01-10 23:58:01
rating_value                            NaN
user_id                                   8
video_id                               5139
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 163, dtype: object
explicit = nan
index = 164 row = rating_date_creation    2018-01-10 23:53:01
rating_value                            NaN
user_id                                   8
video_id                               5142
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 164, dtype: object
explicit = nan
index = 165 row = rating_date_creation    2018-01-10 23:43:01
rating_value                            NaN
user_id                                   8
video_id                               5144
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 165, dtype: object
explicit = nan
index = 166 row = rating_date_creation    2018-01-10 23:38:01
rating_value                            NaN
user_id                                   8
video_id                               5149
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 166, dtype: object
explicit = 0.0
explicit = nan
index = 168 row = rating_date_creation    2018-01-10 23:23:01
rating_value                            NaN
user_id                                   8
video_id                               5153
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 168, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 171 row = rating_date_creation    2018-01-10 23:08:01
rating_value                            NaN
user_id                                   8
video_id                               5156
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 171, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 174 row = rating_date_creation    2018-01-10 21:13:01
rating_value                            NaN
user_id                                   8
video_id                               5160
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 174, dtype: object
explicit = 0.0
explicit = nan
index = 176 row = rating_date_creation    2018-01-10 22:53:01
rating_value                            NaN
user_id                                   8
video_id                               5162
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 176, dtype: object
explicit = 0.0
explicit = nan
index = 178 row = rating_date_creation    2018-01-10 22:43:01
rating_value                            NaN
user_id                                   8
video_id                               5168
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 178, dtype: object
explicit = nan
index = 179 row = rating_date_creation    2018-01-10 21:08:01
rating_value                            NaN
user_id                                   8
video_id                               5171
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 179, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 182 row = rating_date_creation    2018-01-10 22:23:05
rating_value                            NaN
user_id                                   8
video_id                               5174
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 182, dtype: object
explicit = nan
index = 183 row = rating_date_creation    2018-01-10 22:18:01
rating_value                            NaN
user_id                                   8
video_id                               5177
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 183, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 186 row = rating_date_creation    2018-01-10 21:58:01
rating_value                            NaN
user_id                                   8
video_id                               5184
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 186, dtype: object
explicit = nan
index = 187 row = rating_date_creation    2018-01-10 21:53:01
rating_value                            NaN
user_id                                   8
video_id                               5185
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 187, dtype: object
explicit = 0.0
explicit = nan
index = 189 row = rating_date_creation    2018-01-10 21:43:01
rating_value                            NaN
user_id                                   8
video_id                               5190
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 189, dtype: object
explicit = 0.0
explicit = nan
index = 191 row = rating_date_creation    2018-01-10 21:28:01
rating_value                            NaN
user_id                                   8
video_id                               5192
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 191, dtype: object
explicit = nan
index = 192 row = rating_date_creation    2018-01-10 21:23:01
rating_value                            NaN
user_id                                   8
video_id                               5194
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 192, dtype: object
explicit = 0.0
explicit = nan
index = 194 row = rating_date_creation    2017-12-09 18:00:00
rating_value                            NaN
user_id                                   9
video_id                               4448
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 194, dtype: object
explicit = nan
index = 195 row = rating_date_creation    2017-12-13 22:00:01
rating_value                            NaN
user_id                                   9
video_id                               4453
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 195, dtype: object
explicit = nan
index = 196 row = rating_date_creation    2017-12-09 10:30:00
rating_value                            NaN
user_id                                   9
video_id                               4454
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 196, dtype: object
explicit = 1.0
index = 197 row = rating_date_creation    2017-12-09 10:00:00
rating_value                              1
user_id                                   9
video_id                               4457
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 197, dtype: object
explicit = 0.0
explicit = nan
index = 199 row = rating_date_creation    2017-12-08 14:00:01
rating_value                            NaN
user_id                                   9
video_id                               4508
video_watch_time                          9
video_watched_type                 injected
rating_implicit                        0.09
rating_explicit                         NaN
overall_rating_value                      0
Name: 199, dtype: object
explicit = nan
index = 200 row = rating_date_creation    2017-12-15 22:30:01
rating_value                            NaN
user_id                                   9
video_id                               4515
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 200, dtype: object
explicit = nan
index = 201 row = rating_date_creation    2017-12-14 21:00:01
rating_value                            NaN
user_id                                   9
video_id                               4550
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 201, dtype: object
explicit = 0.0
explicit = nan
index = 203 row = rating_date_creation    2017-12-08 13:30:00
rating_value                            NaN
user_id                                   9
video_id                               4569
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 203, dtype: object
explicit = nan
index = 204 row = rating_date_creation    2017-12-08 12:30:01
rating_value                            NaN
user_id                                   9
video_id                               4615
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 204, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 207 row = rating_date_creation    2017-12-24 07:00:00
rating_value                            NaN
user_id                                   9
video_id                               4650
video_watch_time                         47
video_watched_type                 injected
rating_implicit                        0.47
rating_explicit                         NaN
overall_rating_value                  0.235
Name: 207, dtype: object
explicit = 0.0
explicit = nan
index = 209 row = rating_date_creation    2017-12-24 05:30:00

explicit = 0.0
explicit = nan
index = 264 row = rating_date_creation    2017-12-14 09:00:00
rating_value                            NaN
user_id                                   9
video_id                               4854
video_watch_time                          1
video_watched_type                 injected
rating_implicit                        0.01
rating_explicit                         NaN
overall_rating_value                      0
Name: 264, dtype: object
explicit = 0.0
explicit = nan
index = 266 row = rating_date_creation    2017-12-13 23:00:01
rating_value                            NaN
user_id                                   9
video_id                               4859
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 266, dtype: object
explicit = nan
index = 267 row = rating_date_creation    2017-12-13 21:00:00
rating_value                            NaN
user_id                                   9
video_id                               4860
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 267, dtype: object
explicit = nan
index = 268 row = rating_date_creation    2017-12-14 08:30:00
rating_value                            NaN
user_id                                   9
video_id                               4877
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 268, dtype: object
explicit = nan
index = 269 row = rating_date_creation    2017-12-15 01:00:01
rating_value                            NaN
user_id                                   9
video_id                               4880
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 269, dtype: object
explicit = nan
index = 270 row = rating_date_creation    2017-12-14 22:30:01
rating_value                            NaN
user_id                                   9
video_id                               4882
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 270, dtype: object
explicit = nan
index = 271 row = rating_date_creation    2017-12-14 21:30:01
rating_value                            NaN
user_id                                   9
video_id                               4883
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 271, dtype: object
explicit = 1.0
index = 272 row = rating_date_creation    2017-12-14 23:30:01
rating_value                              1
user_id                                   9
video_id                               4889
video_watch_time                          5
video_watched_type                 injected
rating_implicit                        0.05
rating_explicit                           1
overall_rating_value                  0.715
Name: 272, dtype: object
explicit = nan
index = 273 row = rating_date_creation    2017-12-15 08:30:01
rating_value                            NaN
user_id                                   9
video_id                               4890
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 273, dtype: object
explicit = nan
index = 274 row = rating_date_creation    2017-12-23 16:30:00
rating_value                            NaN
user_id                                   9
video_id                               4893
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 274, dtype: object
explicit = nan
index = 275 row = rating_date_creation    2017-12-15 21:30:01
rating_value                            NaN
user_id                                   9
video_id                               4894
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 275, dtype: object
explicit = nan
index = 276 row = rating_date_creation    2017-12-15 20:30:01
rating_value                            NaN
user_id                                   9
video_id                               4895
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 276, dtype: object
explicit = nan
index = 277 row = rating_date_creation    2017-12-23 16:00:00
rating_value                            NaN
user_id                                   9
video_id                               4898
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 277, dtype: object
explicit = nan
index = 278 row = rating_date_creation    2017-12-22 20:00:00
rating_value                            NaN
user_id                                   9
video_id                               4905
video_watch_time                          7
video_watched_type                 injected
rating_implicit                        0.07
rating_explicit                         NaN
overall_rating_value                      0
Name: 278, dtype: object
explicit = nan
index = 279 row = rating_date_creation    2017-12-23 15:30:00
rating_value                            NaN
user_id                                   9
video_id                               4906
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 279, dtype: object
explicit = nan
index = 280 row = rating_date_creation    2017-12-23 15:00:00
rating_value                            NaN
user_id                                   9
video_id                               4910
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 280, dtype: object
explicit = 0.0
explicit = nan
index = 282 row = rating_date_creation    2017-12-23 14:00:00
rating_value                            NaN
user_id                                   9
video_id                               4912
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 282, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 285 row = rating_date_creation    2017-12-23 13:00:00
rating_value                            NaN
user_id                                   9
video_id                               4922
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 285, dtype: object
explicit = 0.0
explicit = 0.0
explicit = 0.0
explicit = 0.0
explicit = nan
index = 290 row = rating_date_creation    2017-12-25 10:30:00
rating_value                            NaN
user_id                                   9
video_id                               4987
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 290, dtype: object
explicit = nan
index = 291 row = rating_date_creation    2017-12-26 08:13:00
rating_value                            NaN
user_id                                   9
video_id                               4990
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 291, dtype: object
explicit = 0.0
explicit = 1.0
index = 293 row = rating_date_creation    2017-12-26 10:17:00
rating_value                              1
user_id                                   9
video_id                               4992
video_watch_time                          1
video_watched_type                 injected
rating_implicit                        0.01
rating_explicit                           1
overall_rating_value                  0.703
Name: 293, dtype: object
explicit = nan
index = 294 row = rating_date_creation    2018-01-11 00:36:02
rating_value                            NaN
user_id                                   9
video_id                               4993
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 294, dtype: object
explicit = 0.0
explicit = nan
index = 296 row = rating_date_creation    2018-01-11 00:26:02
rating_value                            NaN
user_id                                   9
video_id                               5000
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 296, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 299 row = rating_date_creation    2018-01-08 19:02:11
rating_value                            NaN
user_id                                   9
video_id                               5005
video_watch_time                         99
video_watched_type                 injected
rating_implicit                        0.99
rating_explicit                         NaN
overall_rating_value                  0.495
Name: 299, dtype: object
explicit = 0.0
explicit = 1.0
index = 301 row = rating_date_creation    2018-01-11 00:06:02
rating_value                              1
user_id                                   9
video_id                               5007
video_watch_time                         62
video_watched_type                 injected
rating_implicit                        0.62
rating_explicit                           1
overall_rating_value                  0.886
Name: 301, dtype: object
explicit = 0.0
explicit = 0.0
explicit = 0.0
explicit = -1.0
index = 305 row = rating_date_creation    2018-01-10 23:01:02
rating_value                             -1
user_id                                   9
video_id                               5065
video_watch_time                         19
video_watched_type                 injected
rating_implicit                        0.19
rating_explicit                          -1
overall_rating_value                 -0.757
Name: 305, dtype: object
explicit = 0.0
explicit = nan
index = 307 row = rating_date_creation    2018-01-04 22:52:37
rating_value                            NaN
user_id                                   9
video_id                               5073
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 307, dtype: object
explicit = 0.0
explicit = 0.0
explicit = nan
index = 310 row = rating_date_creation    2018-01-10 22:11:02
rating_value                            NaN
user_id                                   9
video_id                               5092
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 310, dtype: object
explicit = nan
index = 311 row = rating_date_creation    2018-01-10 22:06:02
rating_value                            NaN
user_id                                   9
video_id                               5094
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 311, dtype: object
explicit = nan
index = 312 row = rating_date_creation    2018-01-10 22:01:02
rating_value                            NaN
user_id                                   9
video_id                               5095
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 312, dtype: object
explicit = nan
index = 313 row = rating_date_creation    2018-01-10 21:56:03
rating_value                            NaN
user_id                                   9
video_id                               5096
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 313, dtype: object
explicit = nan
index = 314 row = rating_date_creation    2018-01-10 21:51:02
rating_value                            NaN
user_id                                   9
video_id                               5100
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 314, dtype: object
explicit = 0.0
explicit = nan
index = 316 row = rating_date_creation    2018-01-10 21:41:02
rating_value                            NaN
user_id                                   9
video_id                               5112
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 316, dtype: object
explicit = -1.0
index = 317 row = rating_date_creation    2018-01-10 21:36:02
rating_value                             -1
user_id                                   9
video_id                               5121
video_watch_time                         11
video_watched_type                 injected
rating_implicit                        0.11
rating_explicit                          -1
overall_rating_value                 -0.733
Name: 317, dtype: object
explicit = 0.0
explicit = 1.0
index = 319 row = rating_date_creation    2018-01-10 21:31:02
rating_value                              1
user_id                                   9
video_id                               5123
video_watch_time                         10
video_watched_type                 injected
rating_implicit                         0.1
rating_explicit                           1
overall_rating_value                   0.73
Name: 319, dtype: object
explicit = nan
index = 320 row = rating_date_creation    2018-01-10 21:15:46
rating_value                            NaN
user_id                                   9
video_id                               5126
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 320, dtype: object
explicit = 0.0
explicit = 1.0
index = 322 row = rating_date_creation    2018-01-09 08:47:13
rating_value                              1
user_id                                   9
video_id                               5135
video_watch_time                         65
video_watched_type                 notified
rating_implicit                        0.65
rating_explicit                           1
overall_rating_value                  0.895
Name: 322, dtype: object
explicit = nan
index = 323 row = rating_date_creation    2018-01-09 08:42:13
rating_value                            NaN
user_id                                   9
video_id                               5138
video_watch_time                         28
video_watched_type                 notified
rating_implicit                        0.28
rating_explicit                         NaN
overall_rating_value                   0.14
Name: 323, dtype: object
explicit = nan
index = 324 row = rating_date_creation    2018-01-07 21:18:39
rating_value                            NaN
user_id                                   9
video_id                               5144
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 324, dtype: object
explicit = nan
index = 325 row = rating_date_creation    2018-01-09 08:04:40
rating_value                            NaN
user_id                                   9
video_id                               5149
video_watch_time                         15
video_watched_type                 notified
rating_implicit                        0.15
rating_explicit                         NaN
overall_rating_value                      0
Name: 325, dtype: object
explicit = -1.0
index = 326 row = rating_date_creation    2018-01-08 18:55:45
rating_value                             -1
user_id                                   9
video_id                               5150
video_watch_time                         13
video_watched_type                 injected
rating_implicit                        0.13
rating_explicit                          -1
overall_rating_value                 -0.739
Name: 326, dtype: object
explicit = 0.0
explicit = nan
index = 328 row = rating_date_creation    2018-01-08 20:03:07
rating_value                            NaN
user_id                                   9
video_id                               5154
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 328, dtype: object
explicit = 1.0
index = 329 row = rating_date_creation    2018-01-08 19:53:07
rating_value                              1
user_id                                   9
video_id                               5156
video_watch_time                          5
video_watched_type                 injected
rating_implicit                        0.05
rating_explicit                           1
overall_rating_value                  0.715
Name: 329, dtype: object
explicit = 0.0
explicit = nan
index = 331 row = rating_date_creation    2018-01-08 19:32:37

explicit = 1.0
index = 362 row = rating_date_creation    2017-12-07 13:30:01
rating_value                              1
user_id                                  18
video_id                               4770
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 362, dtype: object
explicit = nan
index = 363 row = rating_date_creation    2017-12-10 21:00:00
rating_value                            NaN
user_id                                  18
video_id                               4775
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 363, dtype: object
explicit = nan
index = 364 row = rating_date_creation    2017-12-10 20:30:01
rating_value                            NaN
user_id                                  18
video_id                               4776
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 364, dtype: object
explicit = nan
index = 365 row = rating_date_creation    2017-12-10 19:30:00
rating_value                            NaN
user_id                                  18
video_id                               4778
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 365, dtype: object
explicit = 1.0
index = 366 row = rating_date_creation    2017-12-10 15:00:01
rating_value                              1
user_id                                  18
video_id                               4779
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 366, dtype: object
explicit = nan
index = 367 row = rating_date_creation    2017-12-10 10:00:00
rating_value                            NaN
user_id                                  18
video_id                               4782
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 367, dtype: object
explicit = 1.0
index = 368 row = rating_date_creation    2017-12-09 19:30:01
rating_value                              1
user_id                                  18
video_id                               4783
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 368, dtype: object
explicit = nan
index = 369 row = rating_date_creation    2017-12-08 10:00:01
rating_value                            NaN
user_id                                  18
video_id                               4784
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 369, dtype: object
explicit = nan
index = 370 row = rating_date_creation    2017-12-10 09:30:01
rating_value                            NaN
user_id                                  18
video_id                               4785
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 370, dtype: object
explicit = 0.0
explicit = nan
index = 372 row = rating_date_creation    2017-12-09 11:00:01
rating_value                            NaN
user_id                                  18
video_id                               4791
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 372, dtype: object
explicit = nan
index = 373 row = rating_date_creation    2017-12-18 22:30:01
rating_value                            NaN
user_id                                  18
video_id                               4809
video_watch_time                          6
video_watched_type                 injected
rating_implicit                        0.06
rating_explicit                         NaN
overall_rating_value                      0
Name: 373, dtype: object
explicit = nan
index = 374 row = rating_date_creation    2017-12-18 22:00:00
rating_value                            NaN
user_id                                  18
video_id                               4811
video_watch_time                          1
video_watched_type                 injected
rating_implicit                        0.01
rating_explicit                         NaN
overall_rating_value                      0
Name: 374, dtype: object
explicit = 1.0
index = 375 row = rating_date_creation    2017-12-12 23:30:00
rating_value                              1
user_id                                  18
video_id                               4812
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 375, dtype: object
explicit = 1.0
index = 376 row = rating_date_creation    2017-12-12 00:00:00
rating_value                              1
user_id                                  18
video_id                               4813
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 376, dtype: object
explicit = nan
index = 377 row = rating_date_creation    2017-12-18 21:30:01
rating_value                            NaN
user_id                                  18
video_id                               4819
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 377, dtype: object
explicit = 1.0
index = 378 row = rating_date_creation    2017-12-18 21:00:01
rating_value                              1
user_id                                  18
video_id                               4820
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 378, dtype: object
explicit = 1.0
index = 379 row = rating_date_creation    2017-12-13 23:30:01
rating_value                              1
user_id                                  18
video_id                               4823
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 379, dtype: object
explicit = 0.0
explicit = nan
index = 381 row = rating_date_creation    2017-12-13 22:30:01
rating_value                            NaN
user_id                                  18
video_id                               4825
video_watch_time                          1
video_watched_type                 notified
rating_implicit                        0.01
rating_explicit                         NaN
overall_rating_value                      0
Name: 381, dtype: object
explicit = nan
index = 382 row = rating_date_creation    2017-12-13 22:00:01
rating_value                            NaN
user_id                                  18
video_id                               4826
video_watch_time                          1
video_watched_type                 notified
rating_implicit                        0.01
rating_explicit                         NaN
overall_rating_value                      0
Name: 382, dtype: object
explicit = nan
index = 383 row = rating_date_creation    2017-12-13 21:30:01
rating_value                            NaN
user_id                                  18
video_id                               4827
video_watch_time                          1
video_watched_type                 notified
rating_implicit                        0.01
rating_explicit                         NaN
overall_rating_value                      0
Name: 383, dtype: object
explicit = 1.0
index = 384 row = rating_date_creation    2017-12-12 23:00:00
rating_value                              1
user_id                                  18
video_id                               4831
video_watch_time                          1
video_watched_type                 notified
rating_implicit                        0.01
rating_explicit                           1
overall_rating_value                  0.703
Name: 384, dtype: object
explicit = nan
index = 385 row = rating_date_creation    2017-12-12 18:30:00
rating_value                            NaN
user_id                                  18
video_id                               4832
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 385, dtype: object
explicit = 1.0
index = 386 row = rating_date_creation    2017-12-12 22:00:01
rating_value                              1
user_id                                  18
video_id                               4851
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 386, dtype: object
explicit = nan
index = 387 row = rating_date_creation    2017-12-12 22:30:01
rating_value                            NaN
user_id                                  18
video_id                               4852
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 387, dtype: object
explicit = 1.0
index = 388 row = rating_date_creation    2017-12-13 09:30:00
rating_value                              1
user_id                                  18
video_id                               4853
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 388, dtype: object
explicit = nan
index = 389 row = rating_date_creation    2017-12-13 11:30:00
rating_value                            NaN
user_id                                  18
video_id                               4854
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 389, dtype: object
explicit = nan
index = 390 row = rating_date_creation    2017-12-13 18:00:00
rating_value                            NaN
user_id                                  18
video_id                               4859
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 390, dtype: object
explicit = nan
index = 391 row = rating_date_creation    2017-12-13 21:00:01
rating_value                            NaN
user_id                                  18
video_id                               4860
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 391, dtype: object
explicit = 1.0
index = 392 row = rating_date_creation    2017-12-18 20:30:01
rating_value                              1
user_id                                  18
video_id                               4864
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 392, dtype: object
explicit = nan
index = 393 row = rating_date_creation    2017-12-14 08:30:01
rating_value                            NaN
user_id                                  18
video_id                               4877
video_watch_time                        100
video_watched_type                 notified
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 393, dtype: object
explicit = 1.0
index = 394 row = rating_date_creation    2017-12-17 21:00:00
rating_value                              1
user_id                                  18
video_id                               4879
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 394, dtype: object
explicit = 1.0
index = 395 row = rating_date_creation    2017-12-17 20:30:01
rating_value                              1
user_id                                  18
video_id                               4880
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 395, dtype: object
explicit = 1.0
index = 396 row = rating_date_creation    2017-12-15 22:30:01
rating_value                              1
user_id                                  18
video_id                               4881
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 396, dtype: object
explicit = nan
index = 397 row = rating_date_creation    2017-12-14 21:30:01
rating_value                            NaN
user_id                                  18
video_id                               4882
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 397, dtype: object
explicit = nan
index = 398 row = rating_date_creation    2017-12-14 19:00:01
rating_value                            NaN
user_id                                  18
video_id                               4883
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 398, dtype: object
explicit = 1.0
index = 399 row = rating_date_creation    2017-12-15 22:00:01
rating_value                              1
user_id                                  18
video_id                               4889
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 399, dtype: object
explicit = 1.0
index = 400 row = rating_date_creation    2017-12-15 09:00:01
rating_value                              1
user_id                                  18
video_id                               4890
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 400, dtype: object
explicit = 1.0
index = 401 row = rating_date_creation    2017-12-15 21:00:01
rating_value                              1
user_id                                  18
video_id                               4893
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 401, dtype: object
explicit = 1.0
index = 402 row = rating_date_creation    2017-12-15 20:30:01
rating_value                              1
user_id                                  18
video_id                               4894
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 402, dtype: object
explicit = nan
index = 403 row = rating_date_creation    2017-12-15 20:00:01
rating_value                            NaN
user_id                                  18
video_id                               4895
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 403, dtype: object
explicit = nan
index = 404 row = rating_date_creation    2017-12-17 19:30:01
rating_value                            NaN
user_id                                  18
video_id                               4898
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 404, dtype: object
explicit = 1.0
index = 405 row = rating_date_creation    2017-12-17 19:00:00
rating_value                              1
user_id                                  18
video_id                               4905
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                           1
overall_rating_value                      1
Name: 405, dtype: object
explicit = 0.0
explicit = nan
index = 407 row = rating_date_creation    2017-12-18 13:00:01
rating_value                            NaN
user_id                                  18
video_id                               4910
video_watch_time                        100
video_watched_type                 injected
rating_implicit                           1
rating_explicit                         NaN
overall_rating_value                    0.5
Name: 407, dtype: object
explicit = 1.0
index = 408 row = rating_date_creation    2017-12-18 13:30:00
rating_value                              1
user_id                                  18
video_id                               4911
video_watch_time                          4
video_watched_type                 injected
rating_implicit                        0.04
rating_explicit                           1
overall_rating_value                  0.712

In [8]:
# read CSV using a relative path
import pandas as pd
import requests
URL='http://api_mysql.tv4e.pt/api/recommendations/videos'
data= requests.get(URL)
df=pd.DataFrame(data.json())

In [15]:
df[df['video_location'] == '3'].shape

KeyError: 'video_location'

In [ ]:
df.video_location.unique()

In [ ]:
from dateutil import parser
pd.to_datetime(df.video_date_creation)
df=df.sort_values(['video_date_creation'])

datett = df[(df['video_id'] == 4402)].video_date_creation[0]
parser.parse(datett)

# n_recommendations=5
# filtered_recommendations = {video_id: "" for video_id in df[:-n_recommendations-1:-1].video_id}
# filtered_recommendations

In [ ]:
recs = [(video.video_id, video.video_date_creation, "")
                                        for index,video in df[:-5:-1].iterrows()]
recs

In [ ]:
import datetime
now = datetime.datetime.now()
for index,row in df[:-5:-1].iterrows():
    date = parser.parse(row.video_date_creation)
    diff = now-date
    print(diff)

In [ ]:
import dateutil
# read CSV using a relative path
import pandas as pd
import requests
URL='http://api_mysql.tv4e.pt/api/recommendations/videos'
data= requests.get(URL)
df=pd.DataFrame(data.json())
df = df.transpose()
for index, row in df.iterrows():
    print("\n")
    print(row.video_id)
    print(row.video_title)
    print(row.video_desc)
    print(dateutil.parser.parse(row.video_date_creation))
    print(row.video_location)
    print(row.video_asgie_id)
    print(row.video_asgie_title_pt)